USE ECOLOGICAL_DATA;

CREATE TABLE RESEARCHER (
    ORCID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    Name VARCHAR(20) NOT NULL,
    Field VARCHAR(20) NOT NULL,
    PRIMARY KEY(ORCID)
);

CREATE TABLE SPECIES (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    ScientificName VARCHAR(50) NOT NULL,
    ResearcherID INT UNSIGNED,
    PRIMARY KEY(ID),
    FOREIGN KEY(ResearcherID) REFERENCES RESEARCHER(ORCID)
);

CREATE TABLE DIET (
    SpeciesID INT UNSIGNED NOT NULL,
    Diet VARCHAR(20) NOT NULL,
    PRIMARY KEY(SpeciesID, Diet),
    FOREIGN KEY(SpeciesID) REFERENCES SPECIES(ID)
);

CREATE TABLE COMMON_NAME (
    SpeciesID INT UNSIGNED NOT NULL,
    commonName VARCHAR(50) NOT NULL,
    PRIMARY KEY(SpeciesID, commonName),
    FOREIGN KEY(SpeciesID) REFERENCES SPECIES(ID)
);

CREATE TABLE ECOSYSTEM (
    AreaCode VARCHAR(6) NOT NULL,
    AreaKM INT UNSIGNED NOT NULL,
    Location VARCHAR(20) NOT NULL,
    Climate ENUM('Tropical', 'Arid', 'Temperate', 'Continental', 'Polar') NOT NULL,
    Name VARCHAR(20) NOT NULL,
    KeystoneID INT UNSIGNED NOT NULL,
    PRIMARY KEY(AreaCode),
    FOREIGN KEY(KeystoneID) REFERENCES SPECIES(ID)
);

CREATE TABLE STUDENT (
    ORCID INT UNSIGNED NOT NULL,
    Name VARCHAR(20) NOT NULL,
    Course VARCHAR(20) NOT NULL,
    Year INT NOT NULL CHECK (Year BETWEEN 1 AND 5),
    PRIMARY KEY(ORCID, Name),
    FOREIGN KEY(ORCID) REFERENCES RESEARCHER(ORCID)
);

CREATE TABLE INTERACTS_WITH (
    SpeciesID1 INT UNSIGNED NOT NULL,
    SpeciesID2 INT UNSIGNED NOT NULL,
    CHECK (SpeciesID1 <> SpeciesID2),
    Interaction ENUM('Predation', 'Parasitism', 'Symbiosis', 'Commensalism', 'Mutualism', 'Competition') NOT NULL,
    PRIMARY KEY(SpeciesID1, SpeciesID2),
    FOREIGN KEY(SpeciesID1) REFERENCES SPECIES(ID),
    FOREIGN KEY(SpeciesID2) REFERENCES SPECIES(ID)
);

CREATE TABLE LIVES_IN (
    SpeciesID INT UNSIGNED NOT NULL,
    AreaCode VARCHAR(6) NOT NULL,
    PRIMARY KEY(SpeciesID, AreaCode),
    FOREIGN KEY(SpeciesID) REFERENCES SPECIES(ID),
    FOREIGN KEY(AreaCode) REFERENCES ECOSYSTEM(AreaCode)
);